In [2]:
import numpy as np

In [13]:
# ---- THE DATA ----

student_names = np.array(["Aisha", "Ben", "Carla", "Dev", "Eli", "Farah"])   # six students
subject_names = np.array(["Maths", "Physics", "English"])                    # three subjects

scores = np.array([[78, 65, 82],    # Aisha's three marks - one per subject, in the order above
                   [55, 71, 60],    # Ben's
                   [91, 88, 79],    # Carla's
                   [42, 38, 55],    # Dev's
                   [67, 74, 71],    # Eli's
                   [83, 97, 68]])   # Farah's

print(scores)                       # the whole table
print("shape:", scores.shape)

# Name
# Total marks
# Average

[[78 65 82]
 [55 71 60]
 [91 88 79]
 [42 38 55]
 [67 74 71]
 [83 97 68]]
shape: (6, 3)


In [26]:
sum = np.sum(scores, axis=1) 
mean = np.round(np.mean(scores, axis=1), 1)
for i in range(len(student_names)):
    print(f"Name: {student_names[i]}, Total marks:{sum[i]}, Average:{mean[i]}")

Name: Aisha, Total marks:225, Average:75.0
Name: Ben, Total marks:186, Average:62.0
Name: Carla, Total marks:258, Average:86.0
Name: Dev, Total marks:135, Average:45.0
Name: Eli, Total marks:212, Average:70.7
Name: Farah, Total marks:248, Average:82.7


In [34]:
# Subject average
subavg = np.mean(scores, axis=0)
print(subavg)
print(f"Hardest Subject: {subject_names[subavg.argmin()]}")
print(f"Easiest Subject: {subject_names[subavg.argmax()]}")

[69.33333333 72.16666667 69.16666667]
Hardest Subject: English
Easiest Subject: Physics


In [35]:
# Top of the class
print(f"Top of the class is: {student_names[mean.argmax()]}")

Top of the class is: Carla


In [41]:
low_marks = scores<50
at_risk = low_marks.any(axis=1)
print(f"At risk student is: {student_names[at_risk]}")

At risk student is: ['Dev']
