In [1]:
import numpy as np

In [5]:
marks = np.array([35, 68, 75, 86, 29, 95])
print(marks)

[35 68 75 86 29 95]


In [6]:
print(type(marks))

<class 'numpy.ndarray'>


In [10]:
marks2 = np.reshape(marks, (2, 3))
print(marks2)

[[35 68 75]
 [86 29 95]]


In [12]:
mean = np.mean(marks2)
print(mean)

64.66666666666667


In [21]:
mean = np.mean(marks2, axis=0)     #columns mean
print(mean)

[60.5 48.5 85. ]


In [22]:
mean = np.mean(marks2, axis=1)     #rows mean
print(mean)

[59.33333333 70.        ]


In [19]:
transpose = marks2.T
print(transpose)

[[35 86]
 [68 29]
 [75 95]]


In [33]:
marks = np.array([35, 68, 75, 86, 29, 95])
print(marks)
print(marks[(marks<40)|(marks>80)])

[35 68 75 86 29 95]
[35 86 29 95]


In [34]:
grid = np.array([[55, 72, 88], [41, 95, 63], [77, 58, 90]])
print(grid)
# 95
# whole middle row
# whole last column
# top left 2x2 block

[[55 72 88]
 [41 95 63]
 [77 58 90]]


In [35]:
print(grid[1, 1])

95


In [40]:
print(grid[1, :])

[41 95 63]


In [38]:
print(grid[:, 2])

[88 63 90]


In [41]:
print(grid[:2, :2])

[[55 72]
 [41 95]]


In [62]:
students = np.array(["A", "B", "C"])
subjects = np.array([[60, 78.587, 80], [80, 60, 70], [70, 80, 60]])
print(students)
print(subjects)
# students is rows, subjects is columns
# total for each student
# average for each subject, round to 1 decimal place
# highest single mark anywhere in the grid

['A' 'B' 'C']
[[60.    78.587 80.   ]
 [80.    60.    70.   ]
 [70.    80.    60.   ]]


In [63]:
print(subjects.sum(axis=1))

[218.587 210.    210.   ]


In [64]:
print(np.round(subjects.mean(axis=0),1)) 

[70.  72.9 70. ]


In [65]:
print(subjects.max())

80.0


In [84]:
marks = np.array([55, 72, 88, 41, 95, 63])
name = np.array(["Aisha", "Ben", "Carla", "Dev", "Eli", "Farah"])
print(marks)
print(name)

[55 72 88 41 95 63]
['Aisha' 'Ben' 'Carla' 'Dev' 'Eli' 'Farah']


In [85]:
print(name[marks>70])

['Ben' 'Carla' 'Eli']


In [94]:
# sums = (marks[marks>49] & marks[marks<81])

In [95]:
result = np.where(marks>70, "Pass", "Fail")
print(result)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail']
